// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNM4DSXDVYNCWRRJ3oHDTWD8BUfZ4LNc',
    appId: '1:115934502087:web:d2359b454a2e1b0d4432e2',
    messagingSenderId: '115934502087',
    projectId: 'sesame-exchange-app',
    authDomain: 'sesame-exchange-app.firebaseapp.com',
    storageBucket: 'sesame-exchange-app.firebasestorage.app',
    measurementId: 'G-QR3WEFTS72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBld7DeK_AugG3cCx7crLnwKXQzvh_EywE',
    appId: '1:115934502087:android:c2d177e2a099dc784432e2',
    messagingSenderId: '115934502087',
    projectId: 'sesame-exchange-app',
    storageBucket: 'sesame-exchange-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgF43dPQ1-s-crnVqBoP48ISoC-2PhlWc',
    appId: '1:115934502087:ios:3637901a853758b74432e2',
    messagingSenderId: '115934502087',
    projectId: 'sesame-exchange-app',
    storageBucket: 'sesame-exchange-app.firebasestorage.app',
    androidClientId: '115934502087-8m27hglf7dfs8cpq8fdll2h6oaf7v3bq.apps.googleusercontent.com',
    iosClientId: '115934502087-bgaijpqo3ocg3bps0rgqs0beenii9gic.apps.googleusercontent.com',
    iosBundleId: 'com.example.sesameExchangeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgF43dPQ1-s-crnVqBoP48ISoC-2PhlWc',
    appId: '1:115934502087:ios:3637901a853758b74432e2',
    messagingSenderId: '115934502087',
    projectId: 'sesame-exchange-app',
    storageBucket: 'sesame-exchange-app.firebasestorage.app',
    androidClientId: '115934502087-8m27hglf7dfs8cpq8fdll2h6oaf7v3bq.apps.googleusercontent.com',
    iosClientId: '115934502087-bgaijpqo3ocg3bps0rgqs0beenii9gic.apps.googleusercontent.com',
    iosBundleId: 'com.example.sesameExchangeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNM4DSXDVYNCWRRJ3oHDTWD8BUfZ4LNc',
    appId: '1:115934502087:web:191aae7dd23cd1594432e2',
    messagingSenderId: '115934502087',
    projectId: 'sesame-exchange-app',
    authDomain: 'sesame-exchange-app.firebaseapp.com',
    storageBucket: 'sesame-exchange-app.firebasestorage.app',
    measurementId: 'G-KEGFHKP34L',
  );
}
